### PR TITLE
Update llm_client.py

### PR DESCRIPTION
**Pull request by karanveersingh5623**
#47 

Mask the user API keys #47

### CODE REVIEW

**Review by abhimazu — APPROVED** [review]

**Comment by abhimazu** [comment]
Kindly follow the procedure for code merge via branch commits: branch --> release - x.x.x --> pre-release --> main

**Review by abhimazu — CHANGES_REQUESTED** [review]
Kindly follow the procedure for code merge via branch commits: branch --> release - x.x.x --> pre-release --> main

**Comment by abhimazu** [comment]
https://github.com/kubetoolsca/krs/blob/main/CONTRIBUTIONS.md

**Comment by ajeetraina** [comment]
@karanveersingh5623 Can you create a new branch and then raise a PR?

**Review by ajeetraina — APPROVED** [review]

**Pull request merged**
