### PR TITLE
Krs instructions for setting it up on the Kind cluster

### PR DESCRIPTION
**Pull request by OluchukwuON**

### CODE REVIEW

**Comment by ajeetraina** [comment]
@OluchukwuON Did you go through the contribution guidelines ? https://github.com/kubetoolsca/krs/blob/main/CONTRIBUTIONS.md

**Comment by OluchukwuON** [comment]
@ajeetraina I just did. But considering that I already created this branch weeks ago, and made a pull request for digital ocean's blog through this, would it be okay for me to delete it?

**Review by abhimazu — APPROVED** [review]

**Comment by abhimazu** [comment]
Kindly follow the procedure set for code merge branch --> release x.x.x --> pre-release --> main

**Review by abhimazu — CHANGES_REQUESTED** [review]
Kindly follow the procedure set for code merge branch --> release x.x.x --> pre-release --> main

**Comment by abhimazu** [comment]
https://github.com/kubetoolsca/krs/blob/main/CONTRIBUTIONS.md

**Comment by OluchukwuON** [comment]
Noted @abhimazu I will ensure this practice. Thanks!

**Comment by ajeetraina** [comment]
@abhimazu Can you take a look?

**Review by ajeetraina — APPROVED** [review]

**Pull request merged**
